/** @type {import('prettier').Config} */
module.exports = {
  importOrder: [
    '^types$',
    '^type$',
    '<TYPES>',
    '',
    '^(next/(.*)$)|^(next$)',
    '^(react/(.*)$)|^(react$)',
    '^(drizzle-orm/(.*)$)|^(drizzle-orm$)',
    '',
    '<THIRD_PARTY_MODULES>',
    '^@/lib/(.*)$',
    '',
    '^@/utils/(.*)$',
    '',
    '^@/hooks/(.*)$',
    '^@/components/ui/(.*)$',
    '^@/components/(.*)$',
    '',
    '^[./]',
    '^[../]',
  ],
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  plugins: [
    '@ianvs/prettier-plugin-sort-imports',
    'prettier-plugin-tailwindcss',
  ],

  semi: true,
  singleQuote: true,
  jsxSingleQuote: true,
  trailingComma: 'es5',
  printWidth: 80,
  tabWidth: 2,
  importOrderTypeScriptVersion: '5.0.0',
  tailwindConfig: './tailwind.config.ts',
  proseWrap: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
};
