/** TODO: try if it steal works
 * Unified entity identifier type used across the project.
 *
 * ⚠️ When switching this type between `number` and `string` (UUID v7),
 * the following general rules MUST be applied across all related files.
 * (No need to enumerate columns/tables — apply the rules to whatever
 * exists at the time of the switch, including any newly added ones.)
 *
 * ────────────────────────────────────────────────────────────
 * 1) In `db/schema.ts`
 * ────────────────────────────────────────────────────────────
 *  a) Imports:
 *     - For `number`: import `integer` from 'drizzle-orm/pg-core'
 *       and remove the `uuid` import and `generateId` import.
 *     - For `UUID`: enable `uuid` from 'drizzle-orm/pg-core'
 *       and `import { generateUuidV7 as generateId } from '@/lib/id'`
 *       (the `uuid` package is no longer imported anywhere — `lib/id.ts` is
 *       the only generator seam).
 *
 *  b) Primary Key columns in every table:
 *     - number → `id: integer('id').primaryKey().generatedAlwaysAsIdentity()`
 *     - UUID   → `id: uuid('id').primaryKey().$defaultFn(generateId)`
 *
 *  c) Foreign Key columns (any column using `.references(...)`):
 *     Change the column type to match the referenced PK type.
 *     - number → `integer(...).references(() => other.id, ...)`
 *     - UUID   → `uuid(...).references(() => other.id, ...)`
 *
 *  d) Id-related fields without `references` (logical FKs):
 *     Any column that semantically holds an id (e.g. `*Id`, `recordId`,
 *     `contextId`, etc.) must also be changed to match the new type.
 *
 * ────────────────────────────────────────────────────────────
 * 2) In `utils/index.ts`
 * ────────────────────────────────────────────────────────────
 *  a) `validID` function:
 *     - For `number`: replace it with `positiveInt`
 *       (`export const validID = positiveInt;`).
 *     - For `UUID`: use the version that validates against
 *       `UUID_V7_REGEX` and returns a string.
 *
 *  b) `extractIdFromUrl` function:
 *     - For `number`: use the version that matches `/(\d+)$/`
 *       and returns `number | null`.
 *     - For `UUID`: use the version that matches
 *       `/\/([0-9a-f-]{36}|\d+)$/i` and returns `string | null`.
 *
 *  c) `generateUUIDv7`:
 *     - For `number`: not needed (the id is generated by the database).
 *     - For `UUID`: keep it to generate ids before insert.
 *
 * ────────────────────────────────────────────────────────────
 * 3) In `utils/validation/rules.ts`
 * ────────────────────────────────────────────────────────────
 *  a) Inside `getIDSchema`:
 *     - For `number`:
 *         `const schema = z.int(idRequired).min(1, idRequired).max(MAX_ID, idRequired);`
 *     - For `UUID`:
 *         `const schema = z.string(idRequired).min(1, idRequired);`
 *       (prefer adding `.regex(UUID_V7_REGEX, ...)` for strict validation).
 *
 *     In `preprocess`, the fallback is `0` for number and `''` (or null) for UUID.
 *
 *  b) The exported `idSchema` type:
 *     - For `number`: the second type in `ZodPipe` is `z.ZodInt`.
 *     - For `UUID`:   the second type in `ZodPipe` is `z.ZodString`.
 *
 * ────────────────────────────────────────────────────────────
 * General notes
 * ────────────────────────────────────────────────────────────
 *  - After switching, run `bun tsc` to confirm there are no type errors.
 *  - Generate a new migration via drizzle-kit to reflect the column type change
 *    (converting integer ↔ uuid requires rebuilding tables or using an
 *    explicit USING cast in PostgreSQL).
 *  - Check any endpoints or interfaces that handle the id explicitly
 *    as string/number (e.g. params in API routes).
 */
export type EntityID = string;
